openapi: 3.0.0
info:
  title: Show Schedule
  version: 1.0.0
  description: Spesifikasi untuk menampilkan detail jadwal rapat pada API Rapatin.
servers:
  - url: https://api.rapatin.id

paths:
  /schedules/{meeting_id}:
    get:
      tags: [Show Schedule]
      summary: Melihat Detil Jadwal Rapat
      description: |-
        Ambil detail jadwal rapat Zoom.

        - Untuk jadwal **non-recurring**, kirim **`meeting_id`** saja.
        - Untuk jadwal **recurring**:
          - **Tanpa `occurrence_id`** → kembalikan detail jadwal (beserta informasi pengulangan/occurrences jika tersedia).
          - **Dengan `occurrence_id`** → targetkan salah satu occurrence tertentu.
            Nilai `occurrence_id` merujuk ke `data.occurrences[].occurence_id` dari response pembuatan jadwal.
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
            example: "Bearer {token}"
        - in: header
          name: Accept
          required: true
          schema:
            type: string
            example: application/json
        - in: path
          name: meeting_id
          required: true
          schema:
            type: string
            example: "81911244410"
          description: Meeting ID dari sebuah jadwal.
        - in: query
          name: occurrence_id
          required: false
          schema:
            type: string
            example: "1756108800000"
          description: Opsional. Sertakan untuk menargetkan satu occurrence pada jadwal recurring.

      x-codeSamples:
        - lang: cURL
          label: Non-recurring (tanpa occurrence_id)
          source: |
            curl -L \
              --request GET \
              --url 'https://api.rapatin.id/schedules/81911244410' \
              --header 'Authorization: Bearer {token}' \
              --header 'Accept: application/json'
        - lang: cURL
          label: Recurring (dengan occurrence_id)
          source: |
            curl -L \
              --request GET \
              --url 'https://api.rapatin.id/schedules/84727876665?occurrence_id=1756108800000' \
              --header 'Authorization: Bearer {token}' \
              --header 'Accept: application/json'

      responses:
        '200':
          description: Schedule fetched successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScheduleDetailsResponse"
              examples:
                nonRecurring:
                  summary: Non-recurring schedule
                  value:
                    response:
                      status: success
                      status_code: 200
                      message: Schedule fetched successfully
                    data:
                      id: 110
                      topic: "Weekly Team Sync"
                      passcode: "123456"
                      recurring: false
                      start_date: "2025-08-24"
                      start_time: "14:00:00"
                      meeting_id: "81911244410"
                      occurence_id: null
                      join_url: "https://us06web.zoom.us/j/81911244410?pwd=egGYk70ab8DqOGfaGVRdQaAvfEXLSo.1"
                      registration_url: null
                      waiting_room: 1
                      is_meeting_registration: false
                      is_meeting_qna: false
                      is_language_interpretation: false
                      is_mute_participant_upon_entry: true
                      is_req_permission_to_unmute_participants: false
                      editable: true
                      is_used: false
                      total_recurring: 0
                      custom_live_streaming:
                        stream_url: null
                        stream_key: null
                        live_stream_page_url: null
                      created_at: "2025-08-22T01:36:06.000000Z"
                      updated_at: "2025-08-22T01:36:06.000000Z"
                      product:
                        id: 1
                        name: "Meeting 100 Participants"
                        capacity: 100
                      account:
                        id: 13
                        name: "Space 11"
                      recurring_data:
                        total_recurring: 0
                        recurrence: null
                        repeat_interval: null
                        monthly_day: null
                        monthly_week: null
                        weekly_days: null
                        end_type: null
                        end_date: null
                        end_after_type: null
                recurringSeries:
                  summary: Recurring schedule (series + occurrences)
                  value:
                    response:
                      status: success
                      status_code: 200
                      message: Schedule fetched successfully
                    data:
                      id: 93
                      topic: "Recurring Monthly"
                      passcode: "ABC123"
                      recurring: true
                      start_date: "2025-08-25"
                      start_time: "15:00:00"
                      meeting_id: 84727876665
                      occurence_id: "1756108800000"
                      join_url: "https://us06web.zoom.us/j/84727876665?pwd=7E40zfIlAQU5mzvp5PbZbEz2KbfbdR.1"
                      registration_url: null
                      waiting_room: 1
                      is_meeting_registration: false
                      is_meeting_qna: false
                      is_language_interpretation: false
                      is_mute_participant_upon_entry: true
                      is_req_permission_to_unmute_participants: false
                      editable: true
                      is_used: false
                      total_recurring: 6
                      custom_live_streaming:
                        stream_url: null
                        stream_key: null
                        live_stream_page_url: null
                      created_at: "2025-08-22T09:05:53.000000Z"
                      updated_at: "2025-08-22T09:05:54.000000Z"
                      product:
                        id: 2
                        name: "Meeting 300 Participants"
                        capacity: 300
                      account:
                        id: 14
                        name: "Space 16"
                      recurring_data:
                        total_recurring: 6
                        recurrence: 3
                        repeat_interval: 1
                        monthly_day: null
                        monthly_week: null
                        weekly_days: null
                        end_type: end_after_type
                        end_date: null
                        end_after_type: 6
                      occurrences:
                        - id: 98
                          occurence_id: "1769328000000"
                          start_date: "2026-01-25"
                          start_time: "15:00:00"
                          waiting_room: 1
                          editable: true
                          is_used: false
                        - id: 97
                          occurence_id: "1766649600000"
                          start_date: "2025-12-25"
                          start_time: "15:00:00"
                          waiting_room: 1
                          editable: true
                          is_used: false
                        - id: 96
                          occurence_id: "1764057600000"
                          start_date: "2025-11-25"
                          start_time: "15:00:00"
                          waiting_room: 1
                          editable: true
                          is_used: false
                        - id: 95
                          occurence_id: "1761379200000"
                          start_date: "2025-10-25"
                          start_time: "15:00:00"
                          waiting_room: 1
                          editable: true
                          is_used: false
                        - id: 94
                          occurence_id: "1758787200000"
                          start_date: "2025-09-25"
                          start_time: "15:00:00"
                          waiting_room: 1
                          editable: true
                          is_used: false
                        - id: 93
                          occurence_id: "1756108800000"
                          start_date: "2025-08-25"
                          start_time: "15:00:00"
                          waiting_room: 1
                          editable: true
                          is_used: false
        '401':
          description: Unauthorized (token tidak valid)
        '404':
          description: Schedule not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ScheduleDetailsResponse:
      type: object
      properties:
        response:
          type: object
          properties:
            status:
              type: string
              example: success
              description: Status hasil request.
            status_code:
              type: integer
              example: 200
              description: Kode HTTP response.
            message:
              type: string
              example: Schedule fetched successfully
              description: Pesan keberhasilan.
        data:
          type: object
          properties:
            id:
              type: integer
              description: ID internal jadwal.
            topic:
              type: string
              description: Judul/topik meeting.
            passcode:
              type: string
              description: Kode sandi rapat.
            recurring:
              type: boolean
              description: Status apakah jadwal berulang.
            start_date:
              type: string
              format: date
              description: Tanggal pelaksanaan (YYYY-MM-DD).
            start_time:
              type: string
              description: Jam pelaksanaan (HH:MM:SS).
            meeting_id:
              type: string
              description: Meeting ID Zoom.
            occurence_id:
              type: string
              nullable: true
              description: ID occurrence untuk jadwal recurring (jika berlaku).
            join_url:
              type: string
              description: URL untuk bergabung ke ruang Zoom.
            registration_url:
              type: string
              nullable: true
              description: URL pendaftaran peserta (jika registrasi diaktifkan).
            waiting_room:
              type: integer
              description: Status ruang tunggu (1=aktif, 0=nonaktif).
            is_meeting_registration:
              type: boolean
              description: Apakah membutuhkan registrasi peserta.
            is_meeting_qna:
              type: boolean
              description: Status fitur Q&A.
            is_language_interpretation:
              type: boolean
              description: Status fitur juru bahasa.
            is_mute_participant_upon_entry:
              type: boolean
              description: Mute otomatis saat peserta masuk.
            is_req_permission_to_unmute_participants:
              type: boolean
              description: Peserta butuh izin host untuk unmute.
            editable:
              type: boolean
              description: Apakah jadwal bisa diubah; akan `false` jika sudah dipakai.
            is_used:
              type: boolean
              description: Apakah ruang Zoom pernah digunakan.
            total_recurring:
              type: integer
              description: Jumlah total occurrence pada seri (0 untuk non-recurring).
            custom_live_streaming:
              type: object
              properties:
                stream_url: { type: string, nullable: true }
                stream_key: { type: string, nullable: true }
                live_stream_page_url: { type: string, nullable: true }
            created_at:
              type: string
              format: date-time
              description: Waktu pembuatan jadwal.
            updated_at:
              type: string
              format: date-time
              description: Waktu terakhir diperbarui.
            product:
              type: object
              properties:
                id: { type: integer }
                name: { type: string }
                capacity: { type: integer }
              description: Informasi paket/kapasitas meeting.
            account:
              type: object
              properties:
                id: { type: integer }
                name: { type: string }
              description: Akun/space yang digunakan.
            recurring_data:
              type: object
              description: Rincian pengulangan (hanya untuk jadwal recurring).
              properties:
                total_recurring: { type: integer, nullable: true }
                recurrence: { type: integer, nullable: true }
                repeat_interval: { type: integer, nullable: true }
                monthly_day: { type: integer, nullable: true }
                monthly_week: { type: integer, nullable: true }
                weekly_days:
                  type: array
                  items: { type: integer }
                  nullable: true
                end_type: { type: string, nullable: true }
                end_date: { type: string, format: date, nullable: true }
                end_after_type: { type: integer, nullable: true }
            occurrences:
              type: array
              description: Daftar occurrence pada seri (jika ada).
              items:
                type: object
                properties:
                  id: { type: integer }
                  occurence_id: { type: string }
                  start_date: { type: string, format: date }
                  start_time: { type: string }
                  waiting_room: { type: integer }
                  editable: { type: boolean }
                  is_used: { type: boolean }
