openapi: 3.0.0
info:
  title: Update Schedule
  version: 1.0.0
  description: Spesifikasi untuk memperbarui jadwal rapat pada API Rapatin.
servers:
  - url: https://api.rapatin.id

paths:
  /schedules/{meeting_id}:
    put:
      tags: [Update Schedule]
      summary: Update Schedule
      description: |-
        Perbarui jadwal meeting Zoom.

        - Tanpa `occurrence_id` (query) → memperbarui seluruh jadwal:
          - Non-recurring: update jadwal tunggal.
          - Recurring: update seri (semua occurrence ke depan sesuai kebijakan sistem).
        - Dengan `occurrence_id` (query) → memperbarui **satu occurrence** pada jadwal recurring.
          - Saat mengirim `occurrence_id`, bidang pola recurring (`recurrence`, `repeat_interval`, `weekly_days`, `monthly_day`, `monthly_week`, `end_type`, `end_date`, `end_after_type`) akan **diabaikan**.

        **Batasan update (di-validasi server):**
        - **Tidak dapat diubah:** `product_id`, `meeting_id`, `account_id`.
        - `start_date` & `start_time` **tidak dapat diubah** jika `is_used = 1` **atau** tanggal jadwal telah berlalu.
        - PUT bersifat **partial update**: field yang tidak dikirim **tidak diubah**.

        **Petunjuk pengisian `recurring`:**
        - Jika `recurring` = **false** → gunakan skema *One-time* (tanpa bidang pengulangan).
        - Jika `recurring` = **true** → *WAJIB*: `recurrence` (1=Harian, 2=Mingguan, 3=Bulanan), `repeat_interval`, dan `end_type` (`end_date` atau `end_after_type`).
        - Kondisional:
          - `recurrence=2 (Mingguan)` → sertakan `weekly_days`.
          - `recurrence=3 (Bulanan)` → pilih **satu**: `monthly_day` **atau** `monthly_week`.
          - `end_type=end_date` → sertakan `end_date`.
          - `end_type=end_after_type` → sertakan `end_after_type`.
      parameters:
        - in: path
          name: meeting_id
          required: true
          schema:
            type: string
            example: "89757997072"
          description: Zoom Meeting ID dari jadwal.
        - in: query
          name: occurrence_id
          required: false
          schema:
            type: string
            example: "1756260000000"
          description: ID occurrence untuk memperbarui **satu occurrence** pada jadwal recurring.
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
            example: "Bearer {token}"
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            example: application/json

      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: "#/components/schemas/UpdateOneTimeScheduleRequest"
                - $ref: "#/components/schemas/UpdateRecurringScheduleRequest"
            examples:
              updateOneTime:
                summary: Ubah jadwal non-recurring (ubah jam & topik)
                value:
                  recurring: false
                  topic: "Weekly Team Sync (reschedule)"
                  start_date: "2025-08-25"
                  start_time: "15:30"
              updateSeriesRecurringWeekly:
                summary: Ubah seri recurring mingguan (ubah hari & interval)
                value:
                  recurring: true
                  recurrence: 2
                  repeat_interval: 1
                  weekly_days: [2, 4]   # Monday & Wednesday
                  end_type: end_date
                  end_date: "2025-10-01"
              updateSingleOccurrence:
                summary: Ubah satu occurrence (gunakan query occurrence_id)
                value:
                  recurring: true
                  start_date: "2025-08-27"
                  start_time: "10:00"

      x-codeSamples:
        - lang: cURL
          label: Update one-time (tanpa occurrence_id)
          source: |
            curl -L \
              --request PUT \
              --url 'https://api.rapatin.id/schedules/81911244410' \
              --header 'Authorization: Bearer {token}' \
              --header 'Content-Type: application/json' \
              --data '{
                "recurring": false,
                "topic": "Weekly Team Sync (reschedule)",
                "start_date": "2025-08-25",
                "start_time": "15:30"
              }'
        - lang: cURL
          label: Update single occurrence (dengan occurrence_id)
          source: |
            curl -L \
              --request PUT \
              --url 'https://api.rapatin.id/schedules/89757997072?occurrence_id=1756260000000' \
              --header 'Authorization: Bearer {token}' \
              --header 'Content-Type: application/json' \
              --data '{
                "recurring": true,
                "start_time": "10:00"
              }'

      responses:
        '200':
          description: Schedule updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScheduleUpdateSuccessResponse"
              examples:
                updatedOneTime:
                  summary: Berhasil ubah one-time
                  value:
                    response:
                      status: success
                      status_code: 200
                      message: Schedule updated successfully
                    data:
                      id: 110
                      topic: "Weekly Team Sync (reschedule)"
                      passcode: "123456"
                      recurring: false
                      start_date: "2025-08-25"
                      start_time: "15:30:00"
                      meeting_id: "81911244410"
                      occurence_id: null
                      join_url: "https://us06web.zoom.us/j/81911244410?pwd=egGYk70..."
                      registration_url: null
                      waiting_room: 1
                      is_meeting_registration: false
                      is_meeting_qna: false
                      is_language_interpretation: false
                      is_mute_participant_upon_entry: true
                      is_req_permission_to_unmute_participants: false
                      editable: true
                      is_used: false
                      custom_live_streaming:
                        stream_url: null
                        stream_key: null
                        live_stream_page_url: null
                      created_at: "2025-08-22T01:36:06.000000Z"
                      updated_at: "2025-08-23T05:01:00.000000Z"
                      product: { id: 1, name: "Meeting 100 Participants", capacity: 100 }
                      account: { id: 13, name: "Space 11" }
                      recurring_data:
                        total_recurring: 0
                        recurrence: null
                        repeat_interval: null
                        monthly_day: null
                        monthly_week: null
                        weekly_days: null
                        end_type: null
                        end_date: null
                        end_after_type: null
                updatedOccurrence:
                  summary: Berhasil ubah satu occurrence recurring
                  value:
                    response:
                      status: success
                      status_code: 200
                      message: Schedule updated successfully
                    data:
                      id: 112
                      topic: "Weekly Sales Meeting"
                      passcode: "987654"
                      recurring: true
                      start_date: "2025-08-27"
                      start_time: "10:00:00"
                      meeting_id: "89757997072"
                      occurence_id: "1756260000000"
                      join_url: "https://us06web.zoom.us/j/89757997072?pwd=dn3pRow..."
                      registration_url: null
                      waiting_room: 1
                      is_meeting_registration: false
                      is_meeting_qna: true
                      is_language_interpretation: false
                      is_mute_participant_upon_entry: false
                      is_req_permission_to_unmute_participants: true
                      editable: true
                      is_used: false
                      custom_live_streaming:
                        stream_url: null
                        stream_key: null
                        live_stream_page_url: null
                      created_at: "2025-08-22T01:37:01.000000Z"
                      updated_at: "2025-08-23T06:10:00.000000Z"
                      product: { id: 1, name: "Meeting 100 Participants", capacity: 100 }
                      account: { id: 13, name: "Space 11" }
                      recurring_data:
                        total_recurring: 11
                        recurrence: 2
                        repeat_interval: 1
                        monthly_day: null
                        monthly_week: null
                        weekly_days: [3]
                        end_type: end_date
                        end_date: "2025-09-30"
                        end_after_type: null
        '400':
          description: Validation error
        '401':
          description: Unauthorized (token tidak valid)
        '422':
          description: Unprocessable Entity (kombinasi parameter tidak valid / melanggar batasan update)

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    # ---------- REQUEST SCHEMAS ----------
    CommonUpdateFields:
      type: object
      properties:
        topic:
          type: string
          maxLength: 200
          description: Judul/topik meeting.
        passcode:
          type: string
          maxLength: 10
          description: Kode sandi rapat.
        start_date:
          type: string
          format: date
          description: >-
            Tanggal pelaksanaan (YYYY-MM-DD).
            *Tidak dapat diubah jika* `is_used = 1` *atau* tanggal sudah berlalu.
        start_time:
          type: string
          description: >-
            Jam pelaksanaan (format 24 jam, HH:MM).
            *Tidak dapat diubah jika* `is_used = 1` *atau* tanggal sudah berlalu.
        is_meeting_registration:
          type: boolean
          description: Apakah membutuhkan registrasi peserta.
        is_meeting_qna:
          type: boolean
          description: Mengatur aktif tidaknya fitur Q&A di ruang Zoom.
        is_language_interpretation:
          type: boolean
          description: Aktifkan fitur juru bahasa.
        is_mute_participant_upon_entry:
          type: boolean
          description: Mute otomatis saat peserta masuk.
        is_req_permission_to_unmute_participants:
          type: boolean
          description: Peserta membutuhkan izin host untuk melakukan unmute.
      description: >-
        **Catatan:** `product_id`, `meeting_id`, dan `account_id` tidak dapat
        diubah melalui endpoint ini (dibatasi oleh server).

    UpdateOneTimeScheduleRequest:
      allOf:
        - $ref: "#/components/schemas/CommonUpdateFields"
        - type: object
          properties:
            recurring:
              type: boolean
              enum: [false]
              description: Harus **false** untuk one-time schedule.
          required: [recurring]

    UpdateRecurringScheduleRequest:
      allOf:
        - $ref: "#/components/schemas/CommonUpdateFields"
        - type: object
          properties:
            recurring:
              type: boolean
              enum: [true]
              description: Harus **true** untuk recurring meeting.
            recurrence:
              type: integer
              enum: [1, 2, 3]
              description: |-
                Jenis pengulangan:
                - 1 = Harian
                - 2 = Mingguan
                - 3 = Bulanan
            repeat_interval:
              type: integer
              minimum: 1
              description: Interval pengulangan. Harian max 99, Mingguan max 50, Bulanan max 10.
            weekly_days:
              type: array
              items:
                type: integer
                minimum: 1
                maximum: 7
              description: |-
                Hanya untuk **recurrence = 2 (Mingguan)**:
                - 1 = Sunday
                - 2 = Monday
                - 3 = Tuesday
                - 4 = Wednesday
                - 5 = Thursday
                - 6 = Friday
                - 7 = Saturday
            monthly_day:
              type: integer
              minimum: 1
              maximum: 31
              description: "Hanya untuk **recurrence = 3 (Bulanan)**. Alternatif dari **monthly_week**."
            monthly_week:
              type: integer
              enum: [1, 2, 3, 4, 5]
              description: |-
                Hanya untuk **recurrence = 3 (Bulanan)**:
                - 1 = First week
                - 2 = Second week
                - 3 = Third week
                - 4 = Fourth week
                - 5 = Last week
            end_type:
              type: string
              enum: [end_date, end_after_type]
              description: Cara berhenti—berdasarkan tanggal atau jumlah pengulangan.
            end_date:
              type: string
              format: date
              description: Wajib jika **end_type = end_date**.
            end_after_type:
              type: integer
              description: Wajib jika **end_type = end_after_type** (jumlah pengulangan).
          required:
            - recurring
            - recurrence
            - repeat_interval
            - end_type

    # ---------- RESPONSE SCHEMAS ----------
    ScheduleUpdateSuccessResponse:
      type: object
      properties:
        response:
          type: object
          properties:
            status: { type: string, example: success }
            status_code: { type: integer, example: 200 }
            message: { type: string, example: Schedule updated successfully }
        data:
          $ref: "#/components/schemas/ScheduleItemFull"

    # Struktur detail jadwal penuh
    ScheduleItemFull:
      type: object
      properties:
        id: { type: integer }
        topic: { type: string }
        passcode: { type: string }
        recurring: { type: boolean }
        start_date: { type: string, format: date }
        start_time: { type: string }
        meeting_id: { type: string }
        occurence_id: { type: string, nullable: true }
        join_url: { type: string }
        registration_url: { type: string, nullable: true }
        waiting_room: { type: integer }
        is_meeting_registration: { type: boolean }
        is_meeting_qna: { type: boolean }
        is_language_interpretation: { type: boolean }
        is_mute_participant_upon_entry: { type: boolean }
        is_req_permission_to_unmute_participants: { type: boolean }
        editable: { type: boolean }
        is_used: { type: boolean }
        custom_live_streaming:
          type: object
          properties:
            stream_url: { type: string, nullable: true }
            stream_key: { type: string, nullable: true }
            live_stream_page_url: { type: string, nullable: true }
        created_at: { type: string, format: date-time }
        updated_at: { type: string, format: date-time }
        product:
          type: object
          properties:
            id: { type: integer }
            name: { type: string }
            capacity: { type: integer }
        account:
          type: object
          properties:
            id: { type: integer }
            name: { type: string }
        recurring_data:
          type: object
          description: Rincian pengulangan (jika recurring).
          properties:
            total_recurring: { type: integer, nullable: true }
            recurrence: { type: integer, nullable: true }
            repeat_interval: { type: integer, nullable: true }
            monthly_day: { type: integer, nullable: true }
            monthly_week: { type: integer, nullable: true }
            weekly_days:
              type: array
              items: { type: integer }
              nullable: true
            end_type: { type: string, nullable: true }
            end_date: { type: string, format: date, nullable: true }
            end_after_type: { type: integer, nullable: true }
        occurrences:
          type: array
          items:
            type: object
            properties:
              id: { type: integer }
              occurence_id: { type: string }
              start_date: { type: string, format: date }
              start_time: { type: string }
              waiting_room: { type: integer }
              editable: { type: boolean }
              is_used: { type: boolean }
